# Generated by Django 3.1.5 on 2021-07-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock', models.PositiveIntegerField(verbose_name='재고')),
                ('info', models.TextField(verbose_name='상품 정보')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='생성자')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'product',
            },
        ),
    ]
