# Generated by Django 3.1.5 on 2022-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='Nutrition_Facts',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='영양 정보'),
        ),
    ]
