# Generated by Django 3.1.5 on 2022-10-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221005_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buckwheat',
            field=models.BooleanField(default=False, verbose_name='메밀'),
        ),
    ]
