# Generated by Django 3.1.5 on 2022-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetable', '채소'), ('fruit', '과일'), ('nut', '견과'), ('rice', '쌀'), ('fisheries, seafood', '수산,해산'), ('meat, eggs', '정육,계란'), ('Soup, side dish, main dish', '국,반찬,메인요리'), ('salad', '샐러드'), ('noodle', '면'), ('beverage', '음료'), ('Snack', '간식'), ('etc', '기타')], default='etc', max_length=30, verbose_name='카테고리'),
        ),
    ]
