# Generated by Django 3.1.5 on 2022-10-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20221008_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
