# Generated by Django 3.1.5 on 2022-10-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20221008_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Nutrition_Facts',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='영양 정보'),
        ),
    ]
