# Generated by Django 3.1.5 on 2022-10-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20221015_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergy',
            new_name='ProductAllergy',
        ),
    ]
