# Generated by Django 3.1.5 on 2022-10-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20221015_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAllergy',
            new_name='Allergy',
        ),
    ]
