# Generated by Django 3.1.5 on 2022-10-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20221015_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품'),
        ),
    ]
