# Generated by Django 3.1.5 on 2022-10-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20221016_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergy',
        ),
    ]
