# Generated by Django 3.1.5 on 2022-10-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_rate',
            field=models.IntegerField(default=0, verbose_name='판매량'),
        ),
    ]
