# Generated by Django 3.1.5 on 2022-10-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20221030_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy', to='product.product', verbose_name='상품'),
        ),
    ]
