# Generated by Django 3.1.5 on 2022-11-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_allergy_meta_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='metadata',
            name='allergy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allergy', to='product.allergy', verbose_name='알러지'),
            preserve_default=False,
        ),
    ]
