# Generated by Django 3.1.5 on 2022-10-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0020_auto_20221024_1751'),
        ('user', '0004_auto_20221008_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('total_price', models.IntegerField(verbose_name='가격')),
                ('status', models.CharField(choices=[('waiting', '대기'), ('cancel', '취소'), ('finish', '종료')], default='waiting', max_length=30, verbose_name='상태')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_seller', to='user.user', verbose_name='판매자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_orderer', to='user.user', verbose_name='주문자')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
                'db_table': 'cart',
            },
        ),
    ]
