# Generated by Django 3.1.5 on 2022-10-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_degreeofallergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeofallergy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_level', to='user.user', verbose_name='사용자'),
        ),
    ]
