# Generated by Django 3.1.5 on 2022-10-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20221101_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeofallergy',
            name='Big_head',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='대두'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='Mackerel',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='고등어'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='Pork',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='돼지고기'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='Walnut',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='호두'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='beef',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='쇠고기'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='buckwheat',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='메밀'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='chicken',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='닭고기'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='clam',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='조개'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='crab',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='게'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='milk',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='우유'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='peach',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='복숭아'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='peanut',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='땅콩'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='pine_nut',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='잣'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='shrimp',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='새우'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='squid',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='오징어'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='tomato',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='토마토'),
        ),
        migrations.AlterField(
            model_name='degreeofallergy',
            name='wheat',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'High')], default=0, verbose_name='밀'),
        ),
    ]
