# Generated by Django 3.1.5 on 2022-10-24 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221008_1026'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default='admin@test.com', on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='user.user', verbose_name='판매자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to='user.user', verbose_name='주문자'),
        ),
    ]
