# Generated by Django 3.1.5 on 2022-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20221024_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='평점'),
        ),
    ]
